title: audio content analysis
tagline: music information retrieval tasks and applications
description: music information retrieval tasks and applications
show_downloads: false

domain: "audiocontentanalysis.org"
baseurl: ""

author:
  name: alexander lerch
  url: http://www.alexanderlerch.com/

social:
  name: alexander lerch
  links:
    - https://www.linkedin.com/in/lerch
    - https://github.com/alexanderlerch

theme: jekyll-theme-cayman