title: audio content analysis
tagline: music information retrieval tasks and applications
description: music information retrieval tasks and applications
show_downloads: false

domain: "audiocontentanalysis.org"
baseurl: ""

author:
  name: alexander lerch
  url: https://www.alexanderlerch.com/

social:
  name: alexander lerch
  links:
    - https://www.linkedin.com/in/lerch
    - https://github.com/alexanderlerch

theme: jekyll-theme-cayman

#plugins:
#  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md