title: audio content analysis
description: music information retrieval tasks and applications
show_downloads: false

domain: "mir-conferences.audiocontentanalysis.org"
baseurl: ""

theme: jekyll-theme-cayman